<a href="https://colab.research.google.com/github/Jovem-cyber/banco-terminal/blob/main/Scraper%20copa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import requests

url = "https://pt.wikipedia.org/wiki/Lista_de_seleções_campeãs_mundiais_de_futebol#Copa_do_Mundo_de_Futebol_Masculino"

resposta = requests.get(url, headers=headers)
tabelas = pd.read_html(resposta.text)

# Seleciona a primeira tabela
tabela_copa = tabelas[1]

# Exibe a tabela formatada na tela
tabela_copa

tabela_copa = tabela_copa.drop(8)
display(tabela_copa)

/tmp/ipykernel_2523/95781431.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabelas = pd.read_html(resposta.text)

      Seleção                            Títulos
0      Brasil  5 (1958, 1962, 1970, 1994 e 2002)
1      Itália        4 (1934, 1938, 1982 e 2006)
2    Alemanha        4 (1954, 1974, 1990 e 2014)
3   Argentina              3 (1978, 1986 e 2022)
4     Uruguai                    2 (1930 e 1950)
5      França                    2 (1998 e 2018)
6  Inglaterra                           1 (1966)
7     Espanha                           1 (2010)

In [16]:
tabela_copa = tabela_copa.drop(8)
display(tabela_copa)

      Seleção                            Títulos
0      Brasil  5 (1958, 1962, 1970, 1994 e 2002)
1      Itália        4 (1934, 1938, 1982 e 2006)
2    Alemanha        4 (1954, 1974, 1990 e 2014)
3   Argentina              3 (1978, 1986 e 2022)
4     Uruguai                    2 (1930 e 1950)
5      França                    2 (1998 e 2018)
6  Inglaterra                           1 (1966)
7     Espanha                           1 (2010)